import { useEffect, useRef } from "react";
import { cn } from "@shared/index.ts";
import type { Toast } from "../../hooks/useToast.tsx";
import { Check, ErrorOutline } from "@mui/icons-material";

type ToastItemProps = {
  toast: Toast;
  onRemove: (id: number) => void;
};

/** Static class maps — dynamic `border-${type}` strings are not generated by Tailwind. */
const toastStyles = {
  success: {
    wrapper: "border-success/30 bg-success/10 text-success",
    icon: "bg-success/15",
    Icon: Check,
  },
  error: {
    wrapper: "border-error/30 bg-error/10 text-error",
    icon: "bg-error/15",
    Icon: ErrorOutline,
  },
} as const;

function ToastItem({ toast, onRemove }: ToastItemProps) {
  const ref = useRef<HTMLDivElement>(null);
  const { wrapper, icon, Icon } = toastStyles[toast.type];

  useEffect(() => {
    if (!toast.exiting) return;

    const node = ref.current;
    if (!node) return;

    const handleEnd = () => {
      onRemove(toast.id);
    };
    node.addEventListener("animationend", handleEnd);

    return () => {
      node.removeEventListener("animationend", handleEnd);
    };
  }, [toast.exiting, toast.id, onRemove]);

  return (
    <div
      ref={ref}
      className={cn(
        "toast in flex items-center gap-2.5 rounded-xl border bg-white/95 px-4 py-2.5 shadow-xl backdrop-blur-sm",
        wrapper,
        toast.exiting && "out",
      )}
    >
      <span
        className={cn(
          "grid h-6 w-6 shrink-0 place-items-center rounded-full",
          icon,
        )}
      >
        <Icon sx={{ fontSize: 16 }} />
      </span>
      <p className="text-sm font-medium">{toast.message}</p>
    </div>
  );
}

export default ToastItem;

